---
title: "Syllabus"
---

**Course:** ENST/MRNE 222 Environmental Data Science Spring 2025\
**Class time and location:** Tuesdays and Thursdays 9:55-11:10 Goodpaster 197\
**Lab time and location:** Wednesdays 8:00-11:10 River Center Classroom\
**Instructor:** Dr. Cassie Gurbisz (you're welcome to call me Cassie)\
**Email:** cbgurbisz\@smcm.edu\
**Office hours:** Tuesdays 11:30-1:30 Kent Hall 308\
**Website:** https://mrne222-sp25.github.io/website/

## Course description

Today's environmental challenges are increasingly complex and involve vast amounts of data. With technological advances that make ecological measurements cheaper and easier and open science tools that make data more accessible, the environmental field could even be described as "drowning in data." In this course, students will learn how to use tools from statistics and computer science to gain insight from ecological data without "drowning" in it. We will draw practical real-world meaning from complex datasets by interpreting our analyses in the context of previous environmental or marine science coursework. Throughout the course, we will use literate programming and version control tools to ensure that our analyses are reproducible and accessible. We will do all of this using [R](https://cran.r-project.org/), one of the most popular and in-demand statistical programming languages in the environmental and ecological fields.

## Course materials

**Readings:** All of the readings and software in this class are free and publicly available. There are free online versions of all the textbooks, and R, RStudio, and GitHub are also free. Two information sources which we'll use most frequently are:

-   [R 4 Data Science](http://r4ds.had.co.nz/)
-   [Introduction to Modern Statistics](https://openintro-ims.netlify.app/)

**Hardware:** You'll need to bring a laptop to class and lab every day. Make sure to also bring a charger. If you don't have a laptop, please talk with me so we can get you a loaner.

**Software:** For computing, we'll be using Posit Cloud (formerly RStudio Cloud), which lets you access RStudio and all of the packages we'll need right from your browser. Although R and RStudio are freely available to download onto your computer, working from a central cloud version ensures that we spend our class time learning to code rather than trouble shooting software issues. All of your work should be done in our class Posit Cloud RStudio workspace. You will receive an invite to join the workspace during class.

I do recommend that you [download R and RStudio](https://rstudio-education.github.io/hopr/starting.html) onto your computer at some point during the semester since you won't have access to our cloud workspace after the course ends. You might also want to get your computer connected to GitHub so you can ask for help if you run into any problems. [happywithgitr.com](https://happygitwithr.com/) has very good instructions - be sure to follow them carefully and don't skip any steps.

## Learning outcomes

At the completion of this course, students will be able to gain insight from marine and environmental data **reproducibly** and **collaboratively** using **modern programming tools and techniques**.

Specific outcomes include being able to:

-   visualize environmental data using `ggplot2`
-   wrangle and tidy data tables using `dplyr` functions to generate a suitable dataset for analysis
-   use functions and iterative programming to automate analysis tasks
-   define research questions and hypotheses
-   construct statistical models to quantify patterns and make predictions
-   interpret data in the context of prior knowledge in the environmental or marine science domains
-   communicate results and document code using Quarto documents
-   store data and code using a clean and clear system of organization
-   use version control tools (Git and GitHub) to collaborate and share code

## Grading

This is an "ungraded" course. I want you to focus on learning R and developing your quantitative reasoning skills without the stress of losing points over minor mistakes. Mistakes are inevitable in this type of course. In fact, making mistakes and fixing them is the best way to learn! Furthermore, [research has shown](https://www.alfiekohn.org/article/case-grades/) that grading doesn't always improve learning and can sometimes even harm learning.

Rather than submitting work "in exchange" for a letter or number grade, you will self-evaluate most of your assignments by comparing them to the provided solutions documents. In addition, your peers and I will provide qualitative feedback on your projects.

Brief learning reflections will be an important component of most assignments. Periodically throughout the semester, you will also submit more substantial learning reflections in which you give yourself a grade based on your learning, as reflected in the work you submit. This should help you think intentionally about what you're learning, what you're struggling with, and what you need to do to maximize your learning in the course. Hopefully, this will spark your inner motivation to do your best work. As the instructor, I have the final say in your grade. But I rarely find that changing a student's self-assessed grade is necessary - I trust your judgment.

::: callout-important
Your project must meet all of the specifications and you need to make substantial code contributions to your group's work in order to earn at least a C in the course.
:::

## Assessment

### Class preparation

Most weeks, I'll assign a reading that introduces you to the material we'll cover in class. The goal of the readings is to help you get a broad overview of the content so that you become generally familiar with key terms and concepts. The readings are a great reference for completing application exercises, labs, and the course project. Therefore, an additional goal of completing the readings is to familiarize yourself with these resources so you can quickly refer to them when needed.

To incentevize you to do the readings and to help me keep track of who is doing the readings, we will have ungraded "quizzes" in class on the day readings are due.

### Application exercises

Frequently we will work on brief application exercises during class to practice new tools and concepts. The first few will be posted as assignments in our Posit Cloud workspace. When you open an assignment, Posit Cloud will make a copy for you. Your changes will be automatically saved and I'll be able to see your work. After our first lab, you'll clone the remaining Application Exercises from GitHub, work on the in Posit Cloud, and push your changes to GitHub to submit the assignment. Application exercises should be submitted by the end of the week (Friday) in which they were assigned.

### Labs

Labs afford us time to practice the concepts covered in class and work collaboratively on group projects. Some exercises will be relatively brief and can be completed during the designated lab time. Others will be more involved and may need to be finished for homework. Either way, lab assignments should be submitted by the end of the week (Friday) in which they were assigned. At the beginning of each lab, I will typically post a solutions document for the previous lab assignment so you can self-evaluate your work and ask questions.

### Project

Finally, the course also includes an open-ended group project to give you the opportunity for you to demonstrate that you can ask a meaningful research question and apply the tools you have been learning to answer it using real environmental data. You'll identify a topic with which you're familiar from previous coursework to ensure that you have the disciplinary grounding needed to interpret your analysis. Your project must meet all of the specifications provided and you need to make substantial code contributions to your group's work in order to earn at least a C in the course.

::: callout-important
Your project must meet all of the specifications and you need to make substantial code contributions to your group's work in order to earn at least a C in the course.
:::

### Learning reflections

Because this is an ungraded class, we will emphasize qualitative reflection to self-assess your learning. Most if not all of of your assignments will include a reflection component in which you think about what you learned through the assignment, what challenges you faced, etc. At the mid-point and end of the semester, you will write a detailed reflection on your learning and make a case for the grade you have earned based on your progress towards meeting the learning outcomes. Your reflection will describe how your work products (quizzes, application exercises, labs, and project) demonstrates your learning.

An added benefit of this type of reflective work is that it encourages metacognition, which is the ability to think about your own thought processes and how they work. [Research shows](https://www.jstor.org/stable/pdf/43632012.pdf?casa_token=tFS6YefCxDoAAAAA:kw494Wo1BRpRzyAeziXERl200ENBEGqg1ZyjVhKy6iIwC_QE-1RuXcGzMKjoOnP2PMsw15Aqu8g8Yw9iNrmxM50Wek_T5hTUBzkKtwQw5sS16M5awZg) that metacognition can lead to "deeper, more durable, and more transferable learning. Therefore, taking the time to reflection on what and how you learned in the class should actually enhance your learning.

I will provide a mid-term and final reflection template on GitHub for each student to clone in RStudio. You'll submit your reflections by pushing your work back to GitHub.

## More policies

### Attendance and late work

It is very important that you regularly attend class and lab. Everything we do builds on previously covered topics. That means if you miss class or lab, you will fall behind. I also know that life happens! If you need to miss class or lab, first make sure to communicate this with me. Then check the class schedule to see what you missed, review relevant slides and readings, and complete missed assignments on your own. If group-based project work took place, be sure to communicate with your team ASAP to come up with a plan for how you will contribute. Since this is an ungraded course, I will not automatically dock your grade due to absences. However, when you write your mid-semester and final learning reflections, you should carefully consider your attendance record - especially repeated absences - may have impacted your learning and, therefore, your grade.

I encourage you to stick to assignment deadlines - they exist to keep you on track so you don't fall behind with coursework. For all assignments due on Fridays, you have an automatic 2-day extension and can submit them by the end of the day on Sundays (no need to ask). I am also flexible if you really need an additional day or two to complete an assignment. In this case, just ask - it's usually not a problem.

::: callout-important
You need to complete all of the labs assigned before the start of the group project in order to qualify to participate in the group project.
:::

However, you need to complete all of the labs assigned before the start of the group project in order to qualify to participate in the group project. Because the labs are designed to help you learn and practice key coding and analysis concepts, they play an important role in preparing you for the group data projects. It wouldn't be fair to your group members if you are not prepared to contribute meaningfully to the project. If you do not complete all of the labs leading up the the group project, you'll need to complete the project on your own, which means you won't be able to demonstrate one of the central course learning outcomes: collaborative coding. This is something you will need to consider in your learning reflections.

### Use of AI

Google is your friend and you should absolutely use it to help figure out coding questions, problems, bugs, etc. However, I'm a bit wary of AI tools like ChatGPT. It can generate R code, but how much are you really going to learn if you blindly copy and paste whatever code ChatGPT generates? I want you to come away from this course being able to write your own code. ChatGPT can certainly generate simple code for you, but it is pretty bad at solving more complex coding problems. If you don't understand how to write and debug basic code because ChatGPT gave you the answer, you'll never be able to do the type of more advanced work that ChatGPT isn't capable of doing for you.

I don't want to outright ban AI tools, but please be cognizant of your learning. Don't let ChatGPT make you dumb, and critically evaluate whether it's giving you [garbage](https://link.springer.com/article/10.1007/s10676-024-09775-5) or something useful. And if you do use code from a source other than your own brain, whether it be AI, a help forum, or blog, please give attribution to the source.

### Engaged learning

SMCM has recently decreased the amount of time allocated to class meetings. In order to maintain the depth of learning that is required for a 4-credit course, some of your learning will take place by engaging with class material outside of normal lecture hours. Because the course includes a lab period, most of our "engaged learning" will take place via hands-on activities during lab.

### Office hours

Office hours are set times dedicated to students. This means that I will be in my office waiting for you to come by talk to me during that time!

## SMCM resources {.unnumbered}

**Accommodations and Accessibility:** SMCM is committed to providing access to the learning and living experience to students with disabilities and disabling health conditions. If you have received a letter from the Office of Accessibility Services (OAS), which outlines the academic accommodations to which you are entitled to and you want those accommodations to apply to this course, you MUST share your letter and meet with me to review that letter. If you suspect that you have a learning or living need related to a disability or disabling health condition that could benefit from accommodations, you should contact the Office of Accessibility Services, who can help you learn more about how to proceed. Email: adasupport\@smcm.edu

**Office of Student Success Services:** The Office of Student Success Services (OS3) connects students to the resources, activities, services, and programs that can help students be successful, thrive, and persist to graduation. OS3 provides free tutoring services and academic coaching (strategies for time management, getting organized, overcoming procrastination, note-taking, test-taking, study skills, sleep and stress management, etc.) with professional staff and Peer Academic Success Strategies (PASS) Specialists. You may make appointments by emailing PASS\@smcm.edu. To request tutoring for a specific course, email tutoring\@smcm.edu. For any other help call 240-895-4388, stop by Glendening 230, or email os3\@smcm.edu. Asking for help is an important skill to learn. Students who seek assistance and use the resources we have on campus tend to do better academically, socially, and emotionally than the students who do not ask for help or use the resources. Let us provide assistance and support when you need it.

**The Writing and Speaking Center:** Located on the first floor of the main Library, the Writing & Speaking Center offers free peer tutoring in writing and speaking. The peer tutors are students themselves, but they have completed extensive hands-on training to learn how to assist their peers at any step of the process (planning, drafting, or revising) for any writing or speaking assignment. The peer tutors will not make decisions about revision for you and will instead work collaboratively with you to discuss ideas and consider options so that you can choose how best to revise on your own. This collaborative approach is one of the best ways to help students develop their abilities because all writers and speakers need audiences---just ask the peer tutors, who often schedule tutorials with each other. To make an appointment, please visit www.smcm.edu/writingcenter and click the "Schedule an Appointment" button. If you have questions or need assistance, please contact Interim Director Amanda Taylor at apheatwole\@smcm.edu.

**Office of Title IX Compliance and Training:** St. Mary's College of Maryland is committed to helping create a safe and open learning environment for all students. If you (or someone you know) have experienced any form of Sex Discrimination, know that help and support are available. Sex Discrimination means exclusion from participation in or being denied the benefits of any education program or activity on the basis of sex, including sex stereotypes, sex characteristics, sexual orientation, gender identity, and pregnancy or related conditions. Sex-Based Harassment is a form of Sex Discrimination that includes the following types of conduct: quid pro quo harassment, hostile environment harassment, sexual assault, dating violence, domestic violence, and stalking.

The College strongly encourages all community members to take action, seek support, and report incidents of Sex Discrimination to the Title IX Office. Under Title IX of the Education Amendments of 1972, I am required to disclose information about such Sex Discrimination to the Title IX Office. If you would like to talk to a confidential employee who does not have this reporting responsibility, you can contact SMCM Wellness Center (240) 895-4289.

For more information about reporting options and resources at St. Mary's College of Maryland and the community, please visit the Office of Title IX Compliance and Training.

**Wellness Center:** A growing number of students are experiencing mental health challenges to varying degrees. Doing what you can to stay ahead by wisely taking care of yourself will be a key to succeeding academically. Sometimes mental health challenges can affect your ability to complete required work. For example, a particular assignment might trigger anxiety for you in ways which were not anticipated. Or, maybe it becomes difficult to attend class due to mental health challenges. In any of those cases please come and talk with more or send me an email. I'll listen and do what I can to help. The sooner you share your challenges with me, the better prepared I am to assist you. I am one of many people here at SMCM who care about you and your welfare. For further support, the Wellness Center provides numerous confidential health and counseling services including same day/next day connections to counseling by calling 240-895-4289 or emailing the Director at jljolly\@smcm.edu
